[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

[[guide]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/guide/lorem/"

[[tutorial]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/tutorial/lorem/"

[[main]]
  name = "Docs"
  url = "/docs/prologue/introduction/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 10

# [[main]]
#   name = "Tutorial"
#   url = "/tutorial/lorem/ipsum/"
#   weight = 15

[[main]]
  name = "Get Started"
  weight = 30
  identifier = "get-started"
  url = "/docs/prologue/introduction/"

[[main]]
  name = "Quick Start"
  weight = 40
  identifier = "quick-start"
  url = "/docs/prologue/quick-start/"
  parent = "get-started"

[[main]]
  name = "API"
  weight = 60
  identifier = "api"
  url = "/api/"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/phcode-dev/phoenix"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Discord"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" stroke=\"currentcolor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill=\"#000000\" viewBox=\"0 0 50 50\" width=\"25px\" height=\"25px\"><path d=\"M 18.90625 7 C 18.90625 7 12.539063 7.4375 8.375 10.78125 C 8.355469 10.789063 8.332031 10.800781 8.3125 10.8125 C 7.589844 11.480469 7.046875 12.515625 6.375 14 C 5.703125 15.484375 4.992188 17.394531 4.34375 19.53125 C 3.050781 23.808594 2 29.058594 2 34 C 1.996094 34.175781 2.039063 34.347656 2.125 34.5 C 3.585938 37.066406 6.273438 38.617188 8.78125 39.59375 C 11.289063 40.570313 13.605469 40.960938 14.78125 41 C 15.113281 41.011719 15.429688 40.859375 15.625 40.59375 L 18.0625 37.21875 C 20.027344 37.683594 22.332031 38 25 38 C 27.667969 38 29.972656 37.683594 31.9375 37.21875 L 34.375 40.59375 C 34.570313 40.859375 34.886719 41.011719 35.21875 41 C 36.394531 40.960938 38.710938 40.570313 41.21875 39.59375 C 43.726563 38.617188 46.414063 37.066406 47.875 34.5 C 47.960938 34.347656 48.003906 34.175781 48 34 C 48 29.058594 46.949219 23.808594 45.65625 19.53125 C 45.007813 17.394531 44.296875 15.484375 43.625 14 C 42.953125 12.515625 42.410156 11.480469 41.6875 10.8125 C 41.667969 10.800781 41.644531 10.789063 41.625 10.78125 C 37.460938 7.4375 31.09375 7 31.09375 7 C 31.019531 6.992188 30.949219 6.992188 30.875 7 C 30.527344 7.046875 30.234375 7.273438 30.09375 7.59375 C 30.09375 7.59375 29.753906 8.339844 29.53125 9.40625 C 27.582031 9.09375 25.941406 9 25 9 C 24.058594 9 22.417969 9.09375 20.46875 9.40625 C 20.246094 8.339844 19.90625 7.59375 19.90625 7.59375 C 19.734375 7.203125 19.332031 6.964844 18.90625 7 Z M 18.28125 9.15625 C 18.355469 9.359375 18.40625 9.550781 18.46875 9.78125 C 16.214844 10.304688 13.746094 11.160156 11.4375 12.59375 C 11.074219 12.746094 10.835938 13.097656 10.824219 13.492188 C 10.816406 13.882813 11.039063 14.246094 11.390625 14.417969 C 11.746094 14.585938 12.167969 14.535156 12.46875 14.28125 C 17.101563 11.410156 22.996094 11 25 11 C 27.003906 11 32.898438 11.410156 37.53125 14.28125 C 37.832031 14.535156 38.253906 14.585938 38.609375 14.417969 C 38.960938 14.246094 39.183594 13.882813 39.175781 13.492188 C 39.164063 13.097656 38.925781 12.746094 38.5625 12.59375 C 36.253906 11.160156 33.785156 10.304688 31.53125 9.78125 C 31.59375 9.550781 31.644531 9.359375 31.71875 9.15625 C 32.859375 9.296875 37.292969 9.894531 40.3125 12.28125 C 40.507813 12.460938 41.1875 13.460938 41.8125 14.84375 C 42.4375 16.226563 43.09375 18.027344 43.71875 20.09375 C 44.9375 24.125 45.921875 29.097656 45.96875 33.65625 C 44.832031 35.496094 42.699219 36.863281 40.5 37.71875 C 38.5 38.496094 36.632813 38.84375 35.65625 38.9375 L 33.96875 36.65625 C 34.828125 36.378906 35.601563 36.078125 36.28125 35.78125 C 38.804688 34.671875 40.15625 33.5 40.15625 33.5 C 40.570313 33.128906 40.605469 32.492188 40.234375 32.078125 C 39.863281 31.664063 39.226563 31.628906 38.8125 32 C 38.8125 32 37.765625 32.957031 35.46875 33.96875 C 34.625 34.339844 33.601563 34.707031 32.4375 35.03125 C 32.167969 35 31.898438 35.078125 31.6875 35.25 C 29.824219 35.703125 27.609375 36 25 36 C 22.371094 36 20.152344 35.675781 18.28125 35.21875 C 18.070313 35.078125 17.8125 35.019531 17.5625 35.0625 C 16.394531 34.738281 15.378906 34.339844 14.53125 33.96875 C 12.234375 32.957031 11.1875 32 11.1875 32 C 10.960938 31.789063 10.648438 31.699219 10.34375 31.75 C 9.957031 31.808594 9.636719 32.085938 9.53125 32.464844 C 9.421875 32.839844 9.546875 33.246094 9.84375 33.5 C 9.84375 33.5 11.195313 34.671875 13.71875 35.78125 C 14.398438 36.078125 15.171875 36.378906 16.03125 36.65625 L 14.34375 38.9375 C 13.367188 38.84375 11.5 38.496094 9.5 37.71875 C 7.300781 36.863281 5.167969 35.496094 4.03125 33.65625 C 4.078125 29.097656 5.0625 24.125 6.28125 20.09375 C 6.90625 18.027344 7.5625 16.226563 8.1875 14.84375 C 8.8125 13.460938 9.492188 12.460938 9.6875 12.28125 C 12.707031 9.894531 17.140625 9.296875 18.28125 9.15625 Z M 18.5 21 C 15.949219 21 14 23.316406 14 26 C 14 28.683594 15.949219 31 18.5 31 C 21.050781 31 23 28.683594 23 26 C 23 23.316406 21.050781 21 18.5 21 Z M 31.5 21 C 28.949219 21 27 23.316406 27 26 C 27 28.683594 28.949219 31 31.5 31 C 34.050781 31 36 28.683594 36 26 C 36 23.316406 34.050781 21 31.5 21 Z M 18.5 23 C 19.816406 23 21 24.265625 21 26 C 21 27.734375 19.816406 29 18.5 29 C 17.183594 29 16 27.734375 16 26 C 16 24.265625 17.183594 23 18.5 23 Z M 31.5 23 C 32.816406 23 34 24.265625 34 26 C 34 27.734375 32.816406 29 31.5 29 C 30.183594 29 29 27.734375 29 26 C 29 24.265625 30.183594 23 31.5 23 Z\"></path></svg>"
  url = "https://discord.com/invite/rBpTBPttca"
  post = "v0.1.0"
  weight = 20

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/phcodedev"
  weight = 30

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10

[[logo]]
  name = "Phoenix"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"48px\" height=\"45px\" viewBox=\"0 0 47 45\" version=\"1.1\"><defs><image id=\"image14\" width=\"47\" height=\"45\" xlink:href=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC8AAAAtCAYAAAA+7zKnAAAABmJLR0QA/wD/AP+gvaeTAAACHUlEQVRoge2WP2hTQRzHP+8laZP+MQnS2lYEJ0HUpZ1bhApWaBcbipM4OArOTnUTgpODQwXBuS4iSAW3jk6Ci5MOIkLbkFbDe30vdz+HS2rVWCP+JKXcB4530/2+39997+6Bx+PxeDwej+fosCyEVgiAMaAI9ANBb1V1iTxiWh7wNqyyWCpRAkaBY/xnE6HKKkINy7mm5WntNuvhHWbKTnQRGMKZUEdHfMoWFjCA5XyzyermLdblJjNlV2MAyKO8CzriN6iJBVqjNb9gLasb11iTCpPAMMo7oNWJcVvlHRHDxCAxEAExiPvaTMrJ4AURsAOIRlGdzoPBtqLTeYSkzAN9QE6pppp4+UG84RcDxrIIZBVr6i30h86DYbZ4kQjFg6slvinGie9wcNvz3FbEAi42KtHREm/7hftYPh/UfTFcRTE6WuJ3m3f5OChMYXlzQPYvj0+xjVJ01MQDO1EVEzaYDixrv+l+4VODKyhFR++2cQa2g8cUluaYF8tKp+ynhgpK0dH+aQpwr2geKJgFrkvMPYkJ9j1aX3OGkeADeaD+L8X0rkqHADHQAL5knvME4QaGZF90hkzEJQ5RbH4mxRmoZ1/xMmuYw1JvG7Ds3TqHmgAXoRMyydnkDO+TU0gywmYFMr0W1w3fDZxmLJngdXIcSQeZ7bWwbtkzMD7BQFrmWVzgYa9F/Q1tA6PLEO72sdRrQR6Px+PxeI4c3wBuE+fkWpgq7AAAAABJRU5ErkJggg==\"/></defs><g id=\"surface1\"><path style=\" stroke:none;fill-rule:nonzero;fill:rgb(98.039216%,66.666667%,27.843137%);fill-opacity:1;\" d=\"M 29.964844 6.683594 C 30.050781 6.457031 29.746094 6.308594 29.5625 6.488281 L 21.824219 14.039062 C 21.730469 14.128906 21.726562 14.265625 21.8125 14.347656 L 25.539062 17.828125 C 25.664062 17.945312 25.894531 17.882812 25.957031 17.714844 Z M 29.964844 6.683594 \"/><path style=\" stroke:none;fill-rule:nonzero;fill:rgb(99.607843%,52.156863%,8.235294%);fill-opacity:1;\" d=\"M 20.269531 23.253906 C 20.101562 23.261719 20.007812 23.046875 20.105469 22.871094 L 23.753906 16.253906 C 23.828125 16.121094 23.976562 16.085938 24.074219 16.175781 L 30.507812 22.394531 C 30.65625 22.539062 30.554688 22.847656 30.351562 22.855469 Z M 20.269531 23.253906 \"/><path style=\" stroke:none;fill-rule:nonzero;fill:rgb(99.607843%,58.823529%,8.235294%);fill-opacity:1;\" d=\"M 21.546875 20.75 C 21.378906 20.859375 21.152344 20.746094 21.167969 20.558594 L 21.703125 14.390625 C 21.71875 14.195312 21.980469 14.101562 22.125 14.242188 L 25.714844 17.710938 C 25.816406 17.808594 25.796875 17.972656 25.671875 18.050781 Z M 21.546875 20.75 \"/><path style=\" stroke:none;fill-rule:nonzero;fill:rgb(98.039216%,66.666667%,27.843137%);fill-opacity:1;\" d=\"M 6.722656 22.730469 C 6.484375 22.722656 6.464844 22.378906 6.699219 22.273438 L 16.464844 17.804688 C 16.582031 17.753906 16.707031 17.796875 16.75 17.910156 L 18.503906 22.746094 C 18.5625 22.910156 18.421875 23.101562 18.246094 23.097656 Z M 6.722656 22.730469 \"/><path style=\" stroke:none;fill-rule:nonzero;fill:rgb(99.607843%,52.156863%,8.235294%);fill-opacity:1;\" d=\"M 25.414062 19.808594 C 25.484375 19.652344 25.324219 19.484375 25.128906 19.507812 L 17.75 20.464844 C 17.601562 20.484375 17.511719 20.609375 17.558594 20.734375 L 20.777344 29.164062 C 20.851562 29.359375 21.167969 29.378906 21.253906 29.191406 Z M 25.414062 19.808594 \"/><path style=\" stroke:none;fill-rule:nonzero;fill:rgb(99.607843%,58.823529%,8.235294%);fill-opacity:1;\" d=\"M 22.660156 20.074219 C 22.824219 19.953125 22.804688 19.699219 22.628906 19.644531 L 16.832031 17.824219 C 16.648438 17.765625 16.464844 17.976562 16.535156 18.164062 L 18.332031 22.867188 C 18.382812 23 18.539062 23.042969 18.660156 22.953125 Z M 22.660156 20.074219 \"/><use xlink:href=\"#image14\"/></g></svg>"
  url = "/"
  weight = 10
